version: '3'

networks:
  laravel:

services:
  nginx:
    build:
      context: ./dock
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: '${SERVICE_NAME}-nginx'
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - app
      - redis
    networks:
      - laravel

  # mysql:
  #   image: mysql:5.7..22
  #   container_name: '${SERVICE_NAME}-db'
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "${DB_PORT}:3306"
  #   environment:
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT}
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   networks:
  #     - ${NETWORK_NAME}

  app:
    build:
      context: ./dock
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: '${SERVICE_NAME}-app'
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  composer:
    build:
      context: ./dock
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: '${SERVICE_NAME}-composer'
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - app
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:latest
    container_name: '${SERVICE_NAME}-npm'
    volumes:
      - ./src:/var/www/html
    ports:
      - '${NPM_PORT:-3000}:3000'
      - '${NPM_PORT1:-3001}:3001'
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: ./dock
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: '${SERVICE_NAME}-artisan'
    volumes:
      - ./src:/var/www/html:delegated
    working_dir: /var/www/html
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: '${SERVICE_NAME}-redis'
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    networks:
      - laravel

  